import { ThingTemplate } from "../model/interfaces"

const name = "Megaslot";

export const template: ThingTemplate = {
    name: name,
    thing: {
        id: "<thingId>",
        hostPlaneId: "<hostPlaneId>",
        name: name,
        colors: {}, // all default colors
        sprite: {
            symbol: "🧳",
            size: { w: 198, h: 294 },
            base64: `iVBORw0KGgoAAAANSUhEUgAAAMYAAAEmCAYAAAA5qO9rAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAxqADAAQAAAABAAABJgAAAACGx28YAAAGLklEQVR4Ae3TsQ3AIBAEQaBwd0IX7s9IzpC2hCHjw9HtfPfzDY8AgUtgXT8fAgR+AWEYAoEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTAWHYAIEQEEagOBEQhg0QCAFhBIoTgQOB9gUaui9yrQAAAABJRU5ErkJggg==`,
        },
        physics: {
            box: { w: 198, h: 294, anchor: {x:0, y:0}},
            Z: -1,
        },
        constraints: {
            passable:  true,
            pickable:  false,
            pushable:  false,
            enterable: false,
        },
        planes: {},
        equipment: {
            thingSlot: true,
            thingBackpack: true,
        },
    },
    plane: {
        id: "<planetId>",
        ownerId: "<ownerId>",
        things: {},
        text: "",
    }
}


